# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Grizzle Trend Blog
email: Sessler.Tristan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website created as a creative peice for my portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: SesslerTristan
github_username:  Tristan-Sessler

# Build settings
markdown: kramdown
